import { FeaturedPosts } from 'components/landing/FeaturedPosts';
import { Hero } from 'components/landing/Hero';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Course Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <FeaturedPosts />
    </div>
  );
};

export default Home;
